### ISSUE TITLE
Torch bug (actual problem is the last one)

### ISSUE THREAD

**Issue by m4xig1** [m4xig1/SpExPlus_LibriSpeech#11]
Traceback (most recent call last):
  File "/home/m4xig1/speaker_extraction_SpEx/train.py", line 43, in <module>
    main()
  File "/home/m4xig1/speaker_extraction_SpEx/train.py", line 38, in main
    trainer.run(train_loader, test_loader, 1)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/base.py", line 240, in run
    self.train(trainloader)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/base.py", line 178, in train
    batch = self.compute_loss(batch)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/trainer.py", line 35, in compute_loss
    pred = self.model(batch["mix"], batch["reference"], batch["ref_len"])
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/spex_plus.py", line 167, in forward
    y = self.conv_block_4_other(y)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/cnns.py", line 98, in forward
    y = self.norm1(self.prelu1(y))
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/norm.py", line 52, in forward
    x = self.gamma * (x - mean) / th.sqrt(var + self.eps) + self.beta
RuntimeError: handle_0 INTERNAL ASSERT FAILED at "../c10/cuda/driver_api.cpp":15, please report a bug to PyTorch. 
Traceback (most recent call last):
  File "/home/m4xig1/speaker_extraction_SpEx/train.py", line 43, in <module>
    main()
  File "/home/m4xig1/speaker_extraction_SpEx/train.py", line 38, in main
    trainer.run(train_loader, test_loader, 1)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/base.py", line 240, in run
    self.train(trainloader)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/base.py", line 178, in train
    batch = self.compute_loss(batch)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/trainer.py", line 35, in compute_loss
    pred = self.model(batch["mix"], batch["reference"], batch["ref_len"])
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/spex_plus.py", line 167, in forward
    y = self.conv_block_4_other(y)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/cnns.py", line 98, in forward
    y = self.norm1(self.prelu1(y))
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/norm.py", line 52, in forward
    x = self.gamma * (x - mean) / th.sqrt(var + self.eps) + self.beta
RuntimeError: handle_0 INTERNAL ASSERT FAILED at "../c10/cuda/driver_api.cpp":15, please report a bug to PyTorch.

**Comment by m4xig1** [comment]
this problem can be fixed by updating drivers, now i got a new one

**Comment by m4xig1** [comment]
[i guess](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__VA.html#group__CUDA__VA_1ge489256c107df2a07ddf96d80c86cd9b:~:text=CUresult%20cuMemAddressReserve%20(%20CUdeviceptr*%C2%A0ptr%2C%20size_t%C2%A0size%2C%20size_t%C2%A0alignment%2C%20CUdeviceptr%C2%A0addr%2C%20unsigned%20long%20long%C2%A0flags%20)) i don't have enought ram

**Comment by m4xig1** [comment]
I think the problem is in [line](https://github.com/m4xig1/SpExPlus_LibriSpeech/blob/9194806f7bc1db1b778f293f251142890a718333/trainer/base.py#L178)
because 
```py
with torch.no_grad():
                batch = self.compute_loss(batch)
```
works fine

**Comment by m4xig1** [comment]
so i've reproduced code on my laptop, got pretty the same error

```
Traceback (most recent call last):
  File "/home/m4xig1/speaker_extraction_SpEx/test.py", line 44, in <module>
    main()
  File "/home/m4xig1/speaker_extraction_SpEx/test.py", line 37, in main
    trainer.train(train_loader)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/base.py", line 178, in train
    batch = self.compute_loss(batch)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/trainer.py", line 35, in compute_loss
    pred = self.model(batch["mix"], batch["reference"], batch["ref_len"])
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/spex_plus.py", line 165, in forward
    y = self.conv_block_3_other(y)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/cnns.py", line 98, in forward
    y = self.norm1(self.prelu1(y))
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/norm.py", line 52, in forward
    x = self.gamma * (x - mean) / th.sqrt(var + self.eps) + self.beta
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/home/m4xig1/speaker_extraction_SpEx/test.py", line 44, in <module>
    main()
  File "/home/m4xig1/speaker_extraction_SpEx/test.py", line 37, in main
    trainer.train(train_loader)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/base.py", line 178, in train
    batch = self.compute_loss(batch)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/trainer.py", line 35, in compute_loss
    pred = self.model(batch["mix"], batch["reference"], batch["ref_len"])
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/spex_plus.py", line 165, in forward
    y = self.conv_block_3_other(y)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/cnns.py", line 98, in forward
    y = self.norm1(self.prelu1(y))
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/norm.py", line 52, in forward
    x = self.gamma * (x - mean) / th.sqrt(var + self.eps) + self.beta
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by m4xig1** [comment]
some more logs :D. idk how 2 fix, help pls...
```
INFO:train logger:Train mode
train:   0%|                                                                                                                                                    | 0/5152 [00:15<?, ?it/s]
Traceback (most recent call last):
  File "/home/m4xig1/speaker_extraction_SpEx/test.py", line 44, in <module>
    main()
  File "/home/m4xig1/speaker_extraction_SpEx/test.py", line 37, in main
    trainer.train(train_loader)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/base.py", line 178, in train
    batch = self.compute_loss(batch)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/trainer.py", line 35, in compute_loss
    pred = self.model(batch["mix"], batch["reference"], batch["ref_len"])
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/spex_plus.py", line 163, in forward
    y = self.conv_block_2_other(y)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/cnns.py", line 98, in forward
    y = self.norm1(self.prelu1(y))
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/norm.py", line 52, in forward
    x = self.gamma * (x - mean) / th.sqrt(var + self.eps) + self.beta
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 38.00 MiB. GPU 0 has a total capacity of 4.00 GiB of which 0 bytes is free. Process 168275 has 17179869184.00 GiB memory in use. Process 183554 has 17179869184.00 GiB memory in use. Including non-PyTorch memory, this process has 17179869184.00 GiB memory in use. Of the allocated memory 6.66 GiB is allocated by PyTorch, and 239.56 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/m4xig1/speaker_extraction_SpEx/test.py", line 44, in <module>
    main()
  File "/home/m4xig1/speaker_extraction_SpEx/test.py", line 37, in main
    trainer.train(train_loader)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/base.py", line 178, in train
    batch = self.compute_loss(batch)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/trainer.py", line 35, in compute_loss
    pred = self.model(batch["mix"], batch["reference"], batch["ref_len"])
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/spex_plus.py", line 163, in forward
    y = self.conv_block_2_other(y)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/cnns.py", line 98, in forward
    y = self.norm1(self.prelu1(y))
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m4xig1/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m4xig1/speaker_extraction_SpEx/model/norm.py", line 52, in forward
    x = self.gamma * (x - mean) / th.sqrt(var + self.eps) + self.beta
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 38.00 MiB. GPU 0 has a total capacity of 4.00 GiB of which 0 bytes is free. Process 168275 has 17179869184.00 GiB memory in use. Process 183554 has 17179869184.00 GiB memory in use. Including non-PyTorch memory, this process has 17179869184.00 GiB memory in use. Of the allocated memory 6.66 GiB is allocated by PyTorch, and 239.56 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by m4xig1** [comment]
got the same issue in kaggle
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 38.00 MiB. GPU 0 has a total capacty of 15.89 GiB of which 14.12 MiB is free. Process 3776 has 15.88 GiB memory in use. Of the allocated memory 15.54 GiB is allocated by PyTorch, and 55.13 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
