### ISSUE TITLE
Cross entropy 

### ISSUE THREAD

**Issue by m4xig1** [m4xig1/SpExPlus_LibriSpeech#7]
Cross entropy doesn't work. 
_Traceback (most recent call last):
  File "/home/m4xig1/speaker_extraction_SpEx/train.py", line 42, in <module>
    main()
  File "/home/m4xig1/speaker_extraction_SpEx/train.py", line 37, in main
    trainer.run(train_loader, test_loader, 1)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/base.py", line 219, in run
    logs = self.eval(testloader)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/base.py", line 207, in eval
    batch = self.compute_loss(batch)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/trainer.py", line 33, in compute_loss
    return self.loss.forward(est, batch["target"], batch["speaker_id"], is_train)
  File "/home/m4xig1/speaker_extraction_SpEx/loss/loss.py", line 54, in forward
    ce_loss = F.cross_entropy(pred["logits"], speaker_id)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 3053, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
IndexError: Target 1272 is out of bounds.
Traceback (most recent call last):
  File "/home/m4xig1/speaker_extraction_SpEx/train.py", line 42, in <module>
    main()
  File "/home/m4xig1/speaker_extraction_SpEx/train.py", line 37, in main
    trainer.run(train_loader, test_loader, 1)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/base.py", line 219, in run
    logs = self.eval(testloader)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/base.py", line 207, in eval
    batch = self.compute_loss(batch)
  File "/home/m4xig1/speaker_extraction_SpEx/trainer/trainer.py", line 33, in compute_loss
    return self.loss.forward(est, batch["target"], batch["speaker_id"], is_train)
  File "/home/m4xig1/speaker_extraction_SpEx/loss/loss.py", line 54, in forward
    ce_loss = F.cross_entropy(pred["logits"], speaker_id)
  File "/home/m4xig1/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 3053, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
IndexError: Target 1272 is out of bounds._

It's absurd to do 2000 classes classification with linear model...

**Comment by m4xig1** [comment]
enhanced in latest version, not tested yet

**Comment by m4xig1** [comment]
looks good
